### ISSUE TITLE
station names need to be either caps or small.

### ISSUE THREAD

**Issue by Abhi5h3k** [Mansehej/DelhiMetroAPI#14]
Hi, 

**Issue:** 
I was going through a [project](https://delhimetroapi.herokuapp.com/) (more of a ripoff of your work 😅) that was using your API and found an issue that was raised at your end.

currently, your API raises an internal error (<500>) if the station name does not match the exact case.
example: 

-[ This will raise an error](https://us-central1-delhimetroapi.cloudfunctions.net/route-get?from=aiims&to=INA) : _Error: could not handle the request_

`https://us-central1-delhimetroapi.cloudfunctions.net/route-get?from=aiims&to=INA`

- [While This is fine](https://us-central1-delhimetroapi.cloudfunctions.net/route-get?from=AIIMS&to=INA)

`https://us-central1-delhimetroapi.cloudfunctions.net/route-get?from=AIIMS&to=INA`

I would suggest it would be great if you can either make all the station names to upper case or small case.  That will solve this issue. An API must handle such data inputs. 

keep up the good work 👍

**Comment by Mansehej** [comment]
Hey Abhi,
Nice to see you working on a project that utilizes my API.
Your suggestion is absolutely correct and I will fix it by tonight.
I'll let you know once I have updated it.
Regards,
Mansehej.

**Comment by Mansehej** [comment]
Fixed.
-> Input queries are no longer case sensitive
-> Stations in outputs are always lower case

PS. It would be really appreciated if you could provide credits and a link to this repo upon completion of your project.
Thanks,
Mansehej.
